[package]
name = "Testing"
version = "0.1.0"
authors = ["Scorpion <scorupi819@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"

[build-dependencies]
